[tool.poetry]
name = "qu1ckdr0p2"
version = "1.0.0"
description = "Rapid file hosting."
authors = ["byinarie <byinarie@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "8.1.6"
flask = "2.2.5"
netifaces = "0.11.0"
requests = "2.29.0"
tqdm = "4.64.1"
urllib3 = "1.26.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[build]
include = [
    "certs/**/*",
    "downloads/**/*",
    "LICENSE",
    "mac/**/*",
    "pyproject.toml",
    "README.md",
    "serv.py",
    "config/**/*",
    "img/**/*",
    "linux/**/*",
    "poetry.lock",
    "qu1ckdr0p.code-workspace",
    "requirements.txt",
    "windows/**/*"
]