name: Publish to Test PyPI

on:
  push:
    branches:
      - dev
    paths:
      - 'qu1ckdr0p2/qu1ckdr0p2/serv.py'
      - 'pyproject.toml'
      - 'poetry.lock'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install poetry
    
    - name: Configure Test PyPI Repository
      run: poetry config repositories.testpypi https://test.pypi.org/legacy/

    - name: Debug Token Length
      run: echo "Token length is ${#POETRY_PYPI_TOKEN_TEST_PYPI}"
      env:
        POETRY_PYPI_TOKEN_TEST_PYPI: ${{ secrets.PUBLISH_TO_TEST_PYPI }}

    - name: Build package
      run: poetry build

    - name: Publish package to Test PyPI
      run: poetry publish --repository testpypi
      env:
        POETRY_PYPI_TOKEN_TEST_PYPI: ${{ secrets.PUBLISH_TO_TEST_PYPI }}
