name: Sync Windows Directory

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sync Windows Directory
        if: startsWith(github.repository, 'byinarie/') && github.event_path == 'qu1ckdr0p2/windows'
        run: |
          mkdir -p qu1ckdr0p2/windows
          curl -L -o temp.zip https://github.com/Flangvik/SharpCollection/archive/refs/heads/main.zip
          unzip -o temp.zip -d temp
          rsync -r temp/SharpCollection-main/qu1ckdr0p2/windows/ qu1ckdr0p2/windows/
          rm -r temp temp.zip
