name: Sync Windows Directory

on:
  push:
    branches:
      - main
    paths:
      - 'qu1ckdr0p2/windows/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        run: git clone https://github.com/Flangvik/SharpCollection.git SharpCollection

      - name: Sync Windows Directories
        if: github.repository == 'Flangvik/SharpCollection' && github.event_path == 'SharpCollection'
        run: |
          rsync -a SharpCollection qu1ckdr0p2/windows/
          
      - name: Cleanup
        run: rm -rf temp
